### ISSUE TITLE
FooterBar behavior

### ISSUE THREAD

**Issue by sidsverma** [devunwired/coordinated-effort#1]
Loved the FooterBar behavior example. It moves along with the AppBarLayout. But I am experiencing 1 issue: When both the appbar header as well as the footerbar are hidden, and I touch something in the RecyclerView which triggers a layout refresh, my footerbar comes back up though the appbar header is still hidden. And from this point on, the behavior does not work properly.
Have you experienced this? Is there any way to solve this?

**Comment by devunwired** [comment]
I just committed a layout fix in this behavior (for a different reason) that may be related. You might try this again and see if the problem persists.

**Comment by manuel-martos** [comment]
Hi! 
First of all, congrats for the amazing speech around mastering CoordinatorLayout you recently did for the Droidcon SF 2016. I've learnt a lot from there. As @sidsverma mention, I've also found an issue while losing the focus in the activity and coming back: if the footer was hidden when going to background, it will been shown again when bringing back the activity to foreground. I've been working on fixing this issue and finally simplified the FooterBarBehavior, removing the state variables and just translating vertically the FooterBarLayout. Check the changes in the code bellow:

``` java
package com.example.android.coordinatedeffort.behaviors;

import android.content.Context;
import android.support.design.widget.AppBarLayout;
import android.support.design.widget.CoordinatorLayout;
import android.util.AttributeSet;
import android.view.View;

import com.example.android.coordinatedeffort.widget.FooterBarLayout;

/**
 * Simple layout behavior that will track the state of the AppBarLayout
 * and match its offset for a corresponding footer.
 */
public class FooterBarBehavior extends CoordinatorLayout.Behavior<FooterBarLayout> {
    //Required to instantiate as a default behavior
    public FooterBarBehavior() {
    }

    //Required to attach behavior via XML
    public FooterBarBehavior(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    //This is called to determine which views this behavior depends on
    @Override
    public boolean layoutDependsOn(CoordinatorLayout parent,
                                   FooterBarLayout child,
                                   View dependency) {
        //We are watching changes in the AppBarLayout
        return dependency instanceof AppBarLayout;
    }

    //This is called for each change to a dependent view
    @Override
    public boolean onDependentViewChanged(CoordinatorLayout parent,
                                          FooterBarLayout child,
                                          View dependency) {
        int offset = -dependency.getTop();
        child.setTranslationY(offset);
        return true;
    }
}
```

**Comment by devunwired** [comment]
@manuel-martos From what I can see, the change I committed fixes this problem as well. However, your solution looks cleaner. If you submit this as a PR I can review, test, and merge it. One change I would make is to use `offsetTopAndBottom()` instead of setting the translation. When shifting the actual view position, it's more stable to change the view's layout position.
